Repository mts-lucas/flutter-dex, pull requests merged in 2023-06, with the labels that each got.

#35 Card Responsivo
  flutter_dex/lib/detail/datailPokemon.dart
  flutter_dex/lib/detail/pkmView.dart
  flutter_dex/lib/homepage/homePage.dart
  flutter_dex/lib/main.dart
Labels: enhancement, refactor

#38 Tela de pesquisa pronta
  flutter_dex/assets/images/dexlogo.png
  flutter_dex/lib/components/bottomNavBar.dart
  flutter_dex/lib/components/buttomRegions.dart
  flutter_dex/lib/detail/pkmView.dart
  flutter_dex/lib/homepage/homePage.dart
  flutter_dex/lib/main.dart
  flutter_dex/lib/search/SearchInput.dart
  flutter_dex/lib/search/telaSearch.dart
  flutter_dex/lib/utils/search.dart
  flutter_dex/pubspec.yaml
Labels: enhancement

#40 Corrigindo erro de chave e parentese
  flutter_dex/lib/homepage/homePage.dart
Labels: bug

#42 Feat/issue17 quiz
  flutter_dex/lib/homepage/homePage.dart
  flutter_dex/lib/quiz/quizView.dart
  flutter_dex/lib/quiz/telaQuiz.dart
  flutter_dex/lib/search/SearchInput.dart
  flutter_dex/lib/utils/colors.dart
Labels: enhancement

#44 texto upBar agora é dinamico
  flutter_dex/lib/components/appBar.dart
  flutter_dex/lib/detail/pkmView.dart
  flutter_dex/lib/homepage/homePage.dart
  flutter_dex/lib/quiz/telaQuiz.dart
  flutter_dex/lib/search/telaSearch.dart
Labels: refactor

#45 Modificando filtragem por tipo
  flutter_dex/lib/components/appBar.dart
  flutter_dex/lib/detail/pkmView.dart
  flutter_dex/lib/homepage/cardView.dart
  flutter_dex/lib/homepage/filterPage.dart
  flutter_dex/lib/homepage/homePage.dart
  flutter_dex/lib/search/telaSearch.dart
Labels: enhancement

#47 Cores mudadas para a font não sumir
  flutter_dex/lib/utils/colors.dart
Labels: refactor

#54 Bug do icone corrigido
  flutter_dex/android/app/src/main/AndroidManifest.xml
  flutter_dex/android/app/src/main/res/mipmap-hdpi/round_launcher.png
  flutter_dex/android/app/src/main/res/mipmap-mdpi/round_launcher.png
  flutter_dex/android/app/src/main/res/mipmap-xhdpi/round_launcher.png
  flutter_dex/android/app/src/main/res/mipmap-xxhdpi/round_launcher.png
  flutter_dex/android/app/src/main/res/mipmap-xxxhdpi/round_launcher.png
  flutter_dex/ios/Runner/Info.plist
  flutter_dex/lib/components/buttomQuiz.dart
  flutter_dex/lib/components/buttomRegions.dart
  flutter_dex/lib/components/homeButtom.dart
  flutter_dex/lib/detail/pkmView.dart
  flutter_dex/lib/homepage/filterPage.dart
  flutter_dex/lib/homepage/homePage.dart
  flutter_dex/lib/main.dart
Labels: refactor

#55 docs: add project structure #52
  README.md
  flutter_dex/lib/quiz/quizView.dart
Labels: documentation

#57 Imports corrigidos
  flutter_dex/lib/components/appBar.dart
  flutter_dex/lib/components/bottomNavBar.dart
  flutter_dex/lib/detail/pkmView.dart
  flutter_dex/lib/homepage/filterPage.dart
  flutter_dex/lib/homepage/homePage.dart
  flutter_dex/lib/main.dart
  flutter_dex/lib/quiz/quizView.dart
  flutter_dex/lib/quiz/telaQuiz.dart
  flutter_dex/lib/search/telaSearch.dart
  flutter_dex/lib/utils/dexfonts.dart
  flutter_dex/lib/utils/loading.dart
Labels: refactor

#58 refactor: rename imports #56
  flutter_dex/lib/components/appBar.dart
  flutter_dex/lib/search/telaSearch.dart
Labels: refactor
