Repository mts-lucas/flutter-dex, pull requests merged in 2023-05, with the labels that each got.

#9 Update README
  flutter_dex/README.md
Labels: documentation

#10 Arquivo com todas as cores usadas no projeto
  flutter_dex/lib/utils/colors.dart
Labels: enhancement

#12 Novas dependências
  flutter_dex/pubspec.lock
  flutter_dex/pubspec.yaml
Labels: enhancement

#11 BottomNavBar completa
  flutter_dex/lib/components/homeButtom.dart
  flutter_dex/lib/components/navbar.dart
  flutter_dex/lib/main.dart
Labels: enhancement

#23 Criando AppBar
  flutter_dex/lib/components/appbar.dart
  flutter_dex/lib/main.dart
Labels: enhancement

#27 Criando modelo para os cards de pokemons
  flutter_dex/lib/homepage/homePage.dart
  flutter_dex/lib/utils/captalize.dart
Labels: enhancement

#28 Tela dinamica de Pokemon Individual
  flutter_dex/lib/detail/datailPokemon.dart
  flutter_dex/lib/detail/pkmView.dart
  flutter_dex/lib/main.dart
  flutter_dex/lib/utils/colors.dart
Labels: enhancement

#29 Mudando diretório do readme
  README.md
Labels: documentation, refactor

#31 Nova requisição quando o usuário está no meio da página
  flutter_dex/lib/homepage/homePage.dart
Labels: refactor

#32 Novas fontes
  flutter_dex/fonts/Roboto-Bold.ttf
  flutter_dex/fonts/Roboto-Regular.ttf
  flutter_dex/lib/detail/datailPokemon.dart
  flutter_dex/lib/detail/pkmView.dart
  flutter_dex/lib/utils/dexfonts.dart
  flutter_dex/pubspec.yaml
Labels: enhancement
